Repository pypa/bandersnatch, pull requests merged in 2018-05, with the labels that each got.

#13 Remove broken delete logic
  src/bandersnatch/default.conf
  src/bandersnatch/main.py
  src/bandersnatch/mirror.py
  src/bandersnatch/package.py
  src/bandersnatch/tests/test_main.py
  src/bandersnatch/tests/test_mirror.py
  src/bandersnatch/tests/test_package.py
Labels: bug

#10 Remove .hgignore
  .hgignore
Labels: invalid

#14 Add testing in Python 3.7 to ensure we're ready
  .travis.yml
  bitbucket-pipelines.yml
Labels: enhancement

#16 Implement pep440 blacklisting
  README.md
  doc_requirements.txt
  docs/bandersnatch.rst
  docs/conf.py
  docs/filtering_configuration.md
  docs/index.rst
  docs/installation.md
  docs/mirror_configuration.md
  pytest.ini
  setup.py
  src/bandersnatch/configuration.py
  src/bandersnatch/default.conf
  src/bandersnatch/filter.py
  src/bandersnatch/main.py
  src/bandersnatch/mirror.py
  src/bandersnatch/package.py
  src/bandersnatch/tests/test__bandersnatch_plugins__blacklist_name.py
  src/bandersnatch/tests/test_configuration.py
  src/bandersnatch/tests/test_filter.py
  src/bandersnatch/tests/test_main.py
  src/bandersnatch/tests/test_mirror.py
  src/bandersnatch_filter_plugins/__init__.py
  src/bandersnatch_filter_plugins/blacklist_name.py
Labels: enhancement

#36 Add a project whitelist plugin and tests.
  setup.py
  src/bandersnatch/tests/test__bandersnatch_plugins__whitelist_name.py
  src/bandersnatch/tests/test_filter.py
  src/bandersnatch_filter_plugins/whitelist_name.py
Labels: enhancement
