Repository pypa/bandersnatch, pull requests merged in 2021-09, with the labels that each got.

#1006 Add Storage Documentation
  CHANGES.md
  docs/index.rst
  docs/storage_options.md
Labels: documentation

#1007 Clean Up Deps + Update Unittest running Documentation
  .github/workflows/ci_ubuntu.yml
  docs/CONTRIBUTING.md
  requirements_s3.txt
  setup.cfg
  src/bandersnatch/__init__.py
Labels: enhancement, skip news

#1011 Change tox to use pinned deps
  CHANGES.md
  tox.ini
Labels: bug

#1015 add s3 serving documents
  docs/storage_options.md
Labels: skip news

#1043 Change pyup to run monthly
  .pyup.yml
  CHANGES.md
  requirements_s3.txt
Labels: dependencies
