Repository pypa/bandersnatch, pull requests merged in 2021-04, with the labels that each got.

#887 Move to using asyncio.run
  src/bandersnatch/main.py
  src/bandersnatch/tests/test_master.py
Labels: enhancement, skip news

#889 Fix logging bug in metadata_filter for SizeProjectMetadataFilter
  CHANGES.md
  src/bandersnatch/filter.py
  src/bandersnatch/log.py
  src/bandersnatch_filter_plugins/metadata_filter.py
Labels: bug

#891 Add support to use uvloop
  .github/workflows/uvloop_ci.yml
  CHANGES.md
  setup.cfg
  src/bandersnatch/main.py
Labels: enhancement

#893 Update black from 20.8b1 to 21.4b0
  .pre-commit-config.yaml
  requirements_test.txt
  src/bandersnatch/master.py
  src/bandersnatch/mirror.py
  src/bandersnatch/tests/test_main.py
  src/bandersnatch/tests/test_mirror.py
  src/bandersnatch/utils.py
Labels: skip news

#894 Add a default ThreadPoolExecutor to storage plugin to wrap all IO
  CHANGES.md
  src/bandersnatch/delete.py
  src/bandersnatch/mirror.py
  src/bandersnatch/storage.py
  src/bandersnatch/tests/plugins/test_allowlist_name.py
  src/bandersnatch/tests/test_delete.py
Labels: enhancement

#896 Build arm64 + amd64 Docker images
  .github/workflows/docker_readme.yml
  .github/workflows/docker_upload.yml
  CHANGES.md
Labels: enhancement

#897 Remove legacy support for non PC configuration names
  CHANGES.md
  src/bandersnatch/configuration.py
  src/bandersnatch/filter.py
  src/bandersnatch/tests/test_configuration.py
  src/bandersnatch_filter_plugins/allowlist_name.py
  src/bandersnatch_filter_plugins/blocklist_name.py
Labels: bug, enhancement
