Repository pypa/bandersnatch, pull requests merged in 2022-04, with the labels that each got.

#1113 Doc updates for Swift
  docs/storage_options.md
Labels: documentation, skip news

#1115 Remove deprecated --use-feature=in-tree-build in CI
  .github/workflows/ci.yml
  .github/workflows/ci_ubuntu.yml
Labels: skip news

#1112 Fix all doc links
  docs/CONTRIBUTING.md
  docs/filtering_configuration.md
  docs/storage_options.md
Labels: bug, documentation, skip news
