Repository pypa/bandersnatch, pull requests merged in 2023-01, with the labels that each got.

#1335 Remove PURGE call on StalePage
  CHANGES.md
  src/bandersnatch/master.py
  src/bandersnatch/tests/test_master.py
Labels: bug

#1336 Don't run docker_upload workflow on forks
  .github/workflows/docker_upload.yml
Labels: skip news

#1341 Move Docker to 3.11
  .github/workflows/docker_upload.yml
  CHANGES.md
  Dockerfile
Labels: enhancement
